title: Training Blog  
author: LeighHenderson
description: > # this means to ignore newlines until "baseurl:"
  I'm learning how to host a website on Github Pages

# social links
github_username:  LeighHenderson

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
